---
id: Backup
name: Backup
full: Backup and restore library
description: A library that drives the backup and restore features of Horde applications.
list: dev
type: library
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 2.0.0-alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^8.1
    composer:
      horde/compress: ^3
      horde/exception: ^3
      horde/pack: ^2
      horde/translation: ^3
  optional:
    composer:
      horde/test: ^3
keywords: null
vendor: horde
ci-platform:
  '8.1':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
  '8.2':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
  '8.3':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
  '8.4':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
  '8.5':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
  '8.6':
    - php: '>=7.2'
    - ext-dom
    - ext-hash
    - ext-pcre
    - ext-simplexml
    - ext-spl
ci-platform-flags:
  needs_installer_plugin: false
